/**
 * Fichier: donneesMock.ts
 * Description: Contient les données de démonstration utilisées pour peupler
 * l'application en mode local / hors-ligne. Ces données remplacent le
 * backend Python Eve / MongoDB pendant le développement front-end.
 *
 * Adaptées au contexte camerounais :
 * - Villes : Yaoundé, Douala, Bafoussam, Garoua, Bamenda, Kribi, etc.
 * - Marques : Toyota, Hyundai, Kia, Mercedes, Audi, Mitsubishi, etc.
 * - Devise : Franc CFA (FCFA)
 * - Prix réalistes pour le marché local
 */
import { Utilisateur, Vehicule, Reservation } from '../modeles/types';

/**
 * Liste des utilisateurs de démonstration.
 * Deux loueurs (propriétaires) et trois clients (locataires) avec des
 * noms à consonance camerounaise.
 */
export const UTILISATEURS_MOCK: Utilisateur[] = [
  {
    identifiant: 'utilisateur_001',
    nom: 'Mbarga',
    prenom: 'Jean-Pierre',
    email: 'jean.mbarga@autopartage.cm',
    telephone: '+237 6 95 12 34 56',
    role: 'loueur',
    dateInscription: '2025-03-15T10:00:00Z',
    noteMoyenne: 4.8,
    nombreAvis: 47,
  },
  {
    identifiant: 'utilisateur_002',
    nom: 'Ngo Bessala',
    prenom: 'Sylvie',
    email: 'sylvie.ngobessala@autopartage.cm',
    telephone: '+237 6 77 88 99 00',
    role: 'loueur',
    dateInscription: '2025-01-20T14:30:00Z',
    noteMoyenne: 4.9,
    nombreAvis: 89,
  },
  {
    identifiant: 'utilisateur_003',
    nom: 'Essomba',
    prenom: 'Lucas',
    email: 'lucas.essomba@autopartage.cm',
    telephone: '+237 6 54 32 10 98',
    role: 'client',
    dateInscription: '2026-02-10T09:15:00Z',
  },
  {
    identifiant: 'utilisateur_004',
    nom: 'Atangana',
    prenom: 'Camille',
    email: 'camille.atangana@autopartage.cm',
    telephone: '+237 6 78 90 12 34',
    role: 'client',
    dateInscription: '2026-04-05T16:45:00Z',
  },
];

/**
 * Catalogue de véhicules proposés par les propriétaires.
 * Marques et modèles adaptés au marché camerounais, villes du Cameroun.
 * Prix en francs CFA (FCFA).
 */
export const VEHICULES_MOCK: Vehicule[] = [
  {
    identifiant: 'vehicule_001',
    proprietaireId: 'utilisateur_001',
    marque: 'Toyota',
    modele: 'RAV4',
    annee: 2023,
    categorie: 'suv',
    carburant: 'essence',
    transmission: 'automatique',
    nombrePlaces: 5,
    couleur: 'Gris Argent',
    kilometrage: 18500,
    prixParJour: 35000,
    caution: 150000,
    description:
      'Toyota RAV4 récente en parfait état, idéale pour vos déplacements à Yaoundé et week-ends à Kribi. Confortable, spacieuse et économique.',
    equipements: ['Climatisation', 'GPS', 'Bluetooth', 'Régulateur de vitesse', 'Caméra de recul'],
    photos: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800'],
    ville: 'Yaoundé',
    codePostal: '00000',
    disponible: true,
    dateCreation: '2025-04-01T10:00:00Z',
  },
  {
    identifiant: 'vehicule_002',
    proprietaireId: 'utilisateur_002',
    marque: 'Hyundai',
    modele: 'Tucson',
    annee: 2024,
    categorie: 'suv',
    carburant: 'hybride',
    transmission: 'automatique',
    nombrePlaces: 5,
    couleur: 'Bleu Nacré',
    kilometrage: 8200,
    prixParJour: 45000,
    caution: 200000,
    description:
      'Hyundai Tucson hybride, alliant performance et écologie. Très spacieux et silencieux, parfait pour les longs trajets Douala-Yaoundé.',
    equipements: ['Climatisation auto', 'GPS', 'Apple CarPlay', 'Toit panoramique', 'Aide au stationnement'],
    photos: ['https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800'],
    ville: 'Douala',
    codePostal: '00000',
    disponible: true,
    dateCreation: '2025-06-12T14:20:00Z',
  },
  {
    identifiant: 'vehicule_003',
    proprietaireId: 'utilisateur_001',
    marque: 'Kia',
    modele: 'Picanto',
    annee: 2022,
    categorie: 'citadine',
    carburant: 'essence',
    transmission: 'manuelle',
    nombrePlaces: 5,
    couleur: 'Blanc',
    kilometrage: 32400,
    prixParJour: 18000,
    caution: 80000,
    description:
      'Kia Picanto agile et passe-partout, parfaite pour la ville de Douala. Faible consommation et entretien rigoureux.',
    equipements: ['Climatisation', 'Bluetooth', 'Limitateur de vitesse'],
    photos: ['https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800'],
    ville: 'Douala',
    codePostal: '00000',
    disponible: true,
    dateCreation: '2025-02-18T11:00:00Z',
  },
  {
    identifiant: 'vehicule_004',
    proprietaireId: 'utilisateur_002',
    marque: 'Mercedes-Benz',
    modele: 'Classe C',
    annee: 2024,
    categorie: 'premium',
    carburant: 'diesel',
    transmission: 'automatique',
    nombrePlaces: 5,
    couleur: 'Noir',
    kilometrage: 12500,
    prixParJour: 95000,
    caution: 500000,
    description:
      'Berline Mercedes Classe C, finitions haut de gamme et motorisation puissante. Pour vos déplacements d\'exception à Yaoundé.',
    equipements: ['Cuir', 'GPS', 'Sièges chauffants', 'Toit ouvrant', 'Système audio premium', 'Caméra 360°'],
    photos: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800'],
    ville: 'Yaoundé',
    codePostal: '00000',
    disponible: true,
    dateCreation: '2025-08-05T09:30:00Z',
  },
  {
    identifiant: 'vehicule_005',
    proprietaireId: 'utilisateur_001',
    marque: 'Toyota',
    modele: 'Corolla',
    annee: 2023,
    categorie: 'berline',
    carburant: 'essence',
    transmission: 'manuelle',
    nombrePlaces: 5,
    couleur: 'Rouge',
    kilometrage: 22000,
    prixParJour: 25000,
    caution: 100000,
    description:
      'Toyota Corolla, la berline fiable par excellence. Idéale pour les déplacements professionnels à Bafoussam et environs.',
    equipements: ['Climatisation', 'Bluetooth', 'Radio USB', 'GPS'],
    photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800'],
    ville: 'Bafoussam',
    codePostal: '00000',
    disponible: true,
    dateCreation: '2025-05-22T13:00:00Z',
  },
  {
    identifiant: 'vehicule_006',
    proprietaireId: 'utilisateur_002',
    marque: 'Audi',
    modele: 'Q5',
    annee: 2023,
    categorie: 'premium',
    carburant: 'diesel',
    transmission: 'automatique',
    nombrePlaces: 5,
    couleur: 'Gris',
    kilometrage: 28000,
    prixParJour: 80000,
    caution: 400000,
    description:
      'Audi Q5, le SUV premium par excellence. Confort, tenue de route et raffinement pour vos déplacements d\'affaires.',
    equipements: ['Climatisation auto', 'GPS', 'Apple CarPlay', 'Android Auto', 'Régulateur adaptatif', 'Cuir'],
    photos: ['https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=800'],
    ville: 'Douala',
    codePostal: '00000',
    disponible: true,
    dateCreation: '2025-07-10T15:45:00Z',
  },
  {
    identifiant: 'vehicule_007',
    proprietaireId: 'utilisateur_001',
    marque: 'Mitsubishi',
    modele: 'L200',
    annee: 2022,
    categorie: 'utilitaire',
    carburant: 'diesel',
    transmission: 'manuelle',
    nombrePlaces: 5,
    couleur: 'Blanc',
    kilometrage: 45000,
    prixParJour: 40000,
    caution: 180000,
    description:
      'Mitsubishi L200 pick-up, robuste et puissant. Idéal pour les chantiers, les zones rurales et les transports de matériel.',
    equipements: ['Climatisation', 'Bluetooth', '4x4', 'Benne arrière'],
    photos: ['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800'],
    ville: 'Garoua',
    codePostal: '00000',
    disponible: true,
    dateCreation: '2025-03-10T08:30:00Z',
  },
  {
    identifiant: 'vehicule_008',
    proprietaireId: 'utilisateur_002',
    marque: 'Suzuki',
    modele: 'Vitara',
    annee: 2023,
    categorie: 'suv',
    carburant: 'essence',
    transmission: 'automatique',
    nombrePlaces: 5,
    couleur: 'Vert',
    kilometrage: 19800,
    prixParJour: 30000,
    caution: 120000,
    description:
      'Suzuki Vitara compact et agile, parfait pour les routes de Bamenda. Bonne garde au sol et consommation maîtrisée.',
    equipements: ['Climatisation', 'Bluetooth', 'GPS', 'Caméra de recul'],
    photos: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800'],
    ville: 'Bamenda',
    codePostal: '00000',
    disponible: true,
    dateCreation: '2025-09-15T11:00:00Z',
  },
];

/**
 * Réservations existantes en différents états du cycle de validation.
 * Prix convertis en FCFA.
 */
export const RESERVATIONS_MOCK: Reservation[] = [
  {
    identifiant: 'reservation_001',
    vehiculeId: 'vehicule_001',
    clientId: 'utilisateur_003',
    loueurId: 'utilisateur_001',
    dateDebut: '2026-10-05T10:00:00Z',
    dateFin: '2026-10-08T18:00:00Z',
    nombreJours: 3,
    prixTotal: 105000,
    caution: 150000,
    statut: 'en_attente',
    messageClient: 'Bonjour, je souhaite louer votre Toyota RAV4 pour un week-end à Kribi.',
    dateCreation: '2026-09-20T14:30:00Z',
    lieuPriseEnCharge: 'Aéroport de Yaoundé Nsimalen',
  },
  {
    identifiant: 'reservation_002',
    vehiculeId: 'vehicule_004',
    clientId: 'utilisateur_004',
    loueurId: 'utilisateur_002',
    dateDebut: '2026-10-12T09:00:00Z',
    dateFin: '2026-10-15T19:00:00Z',
    nombreJours: 3,
    prixTotal: 285000,
    caution: 500000,
    statut: 'validee',
    messageClient: 'Réservation pour un déplacement professionnel à Yaoundé.',
    messageLoueur: 'Réservation confirmée, le véhicule sera prêt à 9h. Cordialement.',
    dateCreation: '2026-09-22T11:00:00Z',
    dateValidation: '2026-09-22T18:45:00Z',
    lieuPriseEnCharge: 'Hôtel Hilton, Yaoundé',
  },
  {
    identifiant: 'reservation_003',
    vehiculeId: 'vehicule_003',
    clientId: 'utilisateur_003',
    loueurId: 'utilisateur_001',
    dateDebut: '2026-09-15T10:00:00Z',
    dateFin: '2026-09-17T18:00:00Z',
    nombreJours: 2,
    prixTotal: 36000,
    caution: 80000,
    statut: 'terminee',
    noteClient: 5,
    messageClient: 'Location pour le weekend.',
    messageLoueur: 'Tout s\'est bien passé, merci !',
    dateCreation: '2026-09-01T08:30:00Z',
    dateValidation: '2026-09-01T10:15:00Z',
    lieuPriseEnCharge: 'Carrefour Akwa, Douala',
  },
  {
    identifiant: 'reservation_004',
    vehiculeId: 'vehicule_006',
    clientId: 'utilisateur_004',
    loueurId: 'utilisateur_002',
    dateDebut: '2026-10-20T14:00:00Z',
    dateFin: '2026-10-23T12:00:00Z',
    nombreJours: 3,
    prixTotal: 240000,
    caution: 400000,
    statut: 'refusee',
    messageClient: 'Bonjour, je voudrais louer votre Audi Q5 pour un weekend.',
    messageLoueur: 'Désolé, le véhicule sera en maintenance à ces dates.',
    dateCreation: '2026-09-25T16:20:00Z',
    dateValidation: '2026-09-26T09:00:00Z',
    lieuPriseEnCharge: 'Aéroport de Douala',
  },
];